### ISSUE TITLE
Patching of inputs

### ISSUE THREAD

**Issue by levente-1** [icon-lab/I2I-Mamba#5]
Hi, thank you for sharing the code of your excellent paper!
According to the pre-print, as encoder features get passed into a cmMamba block, they are "first tokenized into non-overlapping patches of size (p, p)". 
Within the code, I do not actually see any patching being called upon, and instead (in line 438 of modules.py) see that the 2D input is just flattened to a 1D array by combining the height and width dimensions of images:

Convert input from (B, C, H, W) to (B, H*W, C)
x = x.float().view(B, C, -1).permute(0, 2, 1)

Does the SSM receive a 1D array of the entire image, or is there additional patching that I am missing?
Thank you!

**Comment by Ofarukatli** [comment]
Actually we are going to share a new version of the paper without no patch, where the ssm will receive 1D array of entire image, you may continue to use code as what is now.

**Comment by Ofarukatli** [comment]
Also we will show an abliation task showing the improvement of using 1d array.
