### ISSUE TITLE
About the processing methods of data sets

### ISSUE THREAD

**Issue by liudelong123123** [icon-lab/I2I-Mamba#6]
For the processing methods of T1, T2, and TD of the data set, I hope you can give relevant codes and processing methods.

**Comment by USBskycrafts** [comment]
And also I am a little confused about the description in the 'Dataset' section. You said that 'x.png is a single image ... it will be 768 pixels horizontally and 256 pixels vertically.' So How can the many-to-one tasks' images be a three channels RGB image? It seems that they are concatenated in the space domain.

**Comment by OmerFarukAtli** [comment]
![27](https://github.com/user-attachments/assets/10e7bbc6-b4a6-4a68-8b4a-1ee736c82de7)
A sample image is this for T1,T2>PD task.

**Comment by tcukur** [comment]
> For the processing methods of T1, T2, and TD of the data set, I hope you can give relevant codes and processing methods.

We will be releasing preprocessing code soon.

**Comment by OmerFarukAtli** [comment]
Now, I add data_preparetion for dataset prepartion for both one-to-one task and many-to-one task.
