### ISSUE TITLE
Code runs Error at models/modules.py  line476 about  .view(1,256,64,64)

### ISSUE THREAD

**Issue by QianMuXiao** [icon-lab/I2I-Mamba#7]
![image](https://github.com/user-attachments/assets/0ba876e0-ea7c-4723-9027-8a611672895d)

 /root/autodl-tmp/I2I-Mamba/models/networks.py:15: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_. init.normal(m.weight.data, 0.0, 0.02) model [I2IMamba_model] was created create web directory ./checkpoints/I2I_Mamba_4090_pre2delay/web... Traceback (most recent call last): File "/root/autodl-tmp/I2I-Mamba/train.py", line 122, in <module> model.optimize_parameters() File "/root/autodl-tmp/I2I-Mamba/models/i2i_mamba_one.py", line 144, in optimize_parameters self.forward() File "/root/autodl-tmp/I2I-Mamba/models/i2i_mamba_one.py", line 101, in forward self.fake_B = self.netG(self.real_A) ^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/autodl-tmp/I2I-Mamba/models/modules.py", line 690, in forward x = self.bottleneck_1(x3) ^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/autodl-tmp/I2I-Mamba/models/modules.py", line 539, in forward mamba_out = self.mamba_layer(x) ^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl return self._call_impl(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl return forward_call(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/root/autodl-tmp/I2I-Mamba/models/modules.py", line 476, in forward mamba_out = output.view(1, 256, 64, 64) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ RuntimeError: shape '[1, 256, 64, 64]' is invalid for input of size 16777216
 
 
 I print the output shape : (16,256,64,64) because I set batchsize to 16 
 
 So I delete the code line 476:mamba_out = output.view(1, 256, 64, 64)
 and change to mamba_out = output
 
 
 I want to know if this place is crucial?
 
 Thx

**Comment by OmerFarukAtli** [comment]
It will reduce the performance of the model probably.

**Comment by USBskycrafts** [comment]
change` mamba_out = output.view(1, 256, 64, 64)` to` mamba_out = output.view(-1, 256, 64, 64)` at models/modules.py:476

**Comment by Ofarukatli** [comment]
> change` mamba_out = output.view(1, 256, 64, 64)` to` mamba_out = output.view(-1, 256, 64, 64)` at models/modules.py:476

USBskycrafts is correct about his suggestion. I update the code as he suggested.

Thank you for your participation, we appreciated it.
